from __future__ import annotations

import tomllib
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal

from pydantic import Field, field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


DEFAULT_REVIEWABLE_EXTENSIONS = frozenset(
    {
        ".c",
        ".cpp",
        ".cs",
        ".css",
        ".dart",
        ".go",
        ".h",
        ".html",
        ".java",
        ".js",
        ".json",
        ".jsx",
        ".kt",
        ".less",
        ".php",
        ".py",
        ".r",
        ".rb",
        ".rs",
        ".scala",
        ".scss",
        ".sh",
        ".sql",
        ".svelte",
        ".swift",
        ".ts",
        ".tsx",
        ".vue",
        ".xml",
        ".yaml",
        ".yml",
    }
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
        populate_by_name=True,
    )

    github_app_id: str | None = Field(default=None, validation_alias="GITHUB_APP_ID")
    github_private_key: str | None = Field(default=None, validation_alias="GITHUB_PRIVATE_KEY")
    github_webhook_secret: str | None = Field(default=None, validation_alias="GITHUB_WEBHOOK_SECRET")
    groq_api_key: str | None = Field(default=None, validation_alias="GROQ_API_KEY")
    openai_api_key: str | None = Field(default=None, validation_alias="OPENAI_API_KEY")
    llm_provider: Literal["groq", "openai"] = Field(default="groq", validation_alias="LLM_PROVIDER")
    fallback_llm_provider: Literal["groq", "openai"] | None = Field(
        default=None,
        validation_alias="FALLBACK_LLM_PROVIDER",
    )
    review_model: str = Field(default="llama-3.3-70b-versatile", validation_alias="REVIEW_MODEL")
    summary_model: str | None = Field(default=None, validation_alias="SUMMARY_MODEL")
    fallback_review_model: str | None = Field(default=None, validation_alias="FALLBACK_REVIEW_MODEL")
    fallback_summary_model: str | None = Field(default=None, validation_alias="FALLBACK_SUMMARY_MODEL")
    port: int = Field(default=3000, validation_alias="PORT")
    environment: str = Field(default="production", validation_alias="NODE_ENV")
    log_level: str = Field(default="INFO", validation_alias="LOG_LEVEL")
    log_format: Literal["plain", "json"] = Field(default="plain", validation_alias="LOG_FORMAT")
    max_files_to_review: int = Field(default=10, validation_alias="MAX_FILES_TO_REVIEW")
    max_file_size_kb: int = Field(default=100, validation_alias="MAX_FILE_SIZE_KB")
    review_timeout_ms: int = Field(default=30000, validation_alias="REVIEW_TIMEOUT_MS")
    max_patch_chars: int = Field(default=12000, validation_alias="MAX_PATCH_CHARS")
    max_file_context_chars: int = Field(default=8000, validation_alias="MAX_FILE_CONTEXT_CHARS")
    max_comments_per_review: int = Field(default=20, validation_alias="MAX_COMMENTS_PER_REVIEW")
    review_simple_changes: bool = Field(default=False, validation_alias="REVIEW_SIMPLE_CHANGES")
    post_review_summary: bool = Field(default=True, validation_alias="POST_REVIEW_SUMMARY")
    enable_incremental_reviews: bool = Field(default=True, validation_alias="ENABLE_INCREMENTAL_REVIEWS")
    enable_conversation: bool = Field(default=True, validation_alias="ENABLE_CONVERSATION")
    enable_test_plan: bool = Field(default=True, validation_alias="ENABLE_TEST_PLAN")
    config_file_path: str = Field(default=".pr_review_agent.toml", validation_alias="CONFIG_FILE_PATH")
    delivery_ttl_seconds: int = Field(default=900, validation_alias="DELIVERY_TTL_SECONDS")
    include_patterns: tuple[str, ...] = Field(default_factory=tuple, validation_alias="INCLUDE_PATTERNS")
    exclude_patterns: tuple[str, ...] = Field(
        default=("*.lock", "package-lock.json", "pnpm-lock.yaml", "yarn.lock"),
        validation_alias="EXCLUDE_PATTERNS",
    )
    bot_aliases: tuple[str, ...] = Field(
        default=("@pr-review-agent", "@agent"),
        validation_alias="BOT_ALIASES",
    )
    ignore_keywords: tuple[str, ...] = Field(
        default=("@agent ignore", "@pr-review-agent ignore"),
        validation_alias="IGNORE_KEYWORDS",
    )
    summary_only_keywords: tuple[str, ...] = Field(
        default=("@agent summary-only", "@pr-review-agent summary-only"),
        validation_alias="SUMMARY_ONLY_KEYWORDS",
    )
    staff_review_commands: tuple[str, ...] = Field(
        default=("/staff-review",),
        validation_alias="STAFF_REVIEW_COMMANDS",
    )
    generated_markers: tuple[str, ...] = Field(
        default=(
            "@generated",
            "generated by",
            "auto-generated",
            "automatically generated",
            "do not edit",
        ),
        validation_alias="GENERATED_MARKERS",
    )
    request_parallelism: int = Field(default=3, validation_alias="REQUEST_PARALLELISM")
    webhook_actions: tuple[str, ...] = Field(
        default=("opened", "synchronize", "reopened", "ready_for_review"),
        validation_alias="WEBHOOK_ACTIONS",
    )
    reviewable_extensions: frozenset[str] = Field(default=DEFAULT_REVIEWABLE_EXTENSIONS)
    fallback_groq_api_key: str | None = Field(default=None, validation_alias="FALLBACK_GROQ_API_KEY")
    fallback_openai_api_key: str | None = Field(default=None, validation_alias="FALLBACK_OPENAI_API_KEY")

    @field_validator(
        "include_patterns",
        "exclude_patterns",
        "bot_aliases",
        "ignore_keywords",
        "summary_only_keywords",
        "staff_review_commands",
        "generated_markers",
        "webhook_actions",
        mode="before",
    )
    @classmethod
    def _parse_csv_values(cls, value: Any) -> tuple[str, ...]:
        if value is None or value == "":
            return ()
        if isinstance(value, str):
            return tuple(item.strip() for item in value.split(",") if item.strip())
        if isinstance(value, (list, tuple, set, frozenset)):
            return tuple(str(item).strip() for item in value if str(item).strip())
        return tuple()

    @field_validator("log_level", mode="before")
    @classmethod
    def _normalize_log_level(cls, value: Any) -> str:
        return str(value or "INFO").upper()

    @property
    def api_key(self) -> str | None:
        if self.llm_provider == "groq":
            return self.groq_api_key
        return self.openai_api_key

    @property
    def fallback_api_key(self) -> str | None:
        if self.fallback_llm_provider == "groq":
            return self.fallback_groq_api_key or self.groq_api_key
        if self.fallback_llm_provider == "openai":
            return self.fallback_openai_api_key or self.openai_api_key
        return None

    @property
    def normalized_private_key(self) -> str | None:
        if not self.github_private_key:
            return None
        return self.github_private_key.replace("\\n", "\n")

    @property
    def resolved_summary_model(self) -> str:
        return self.summary_model or self.review_model

    @property
    def resolved_fallback_review_model(self) -> str:
        return self.fallback_review_model or self.review_model

    @property
    def resolved_fallback_summary_model(self) -> str:
        return self.fallback_summary_model or self.resolved_summary_model

    def missing_runtime_variables(self) -> tuple[str, ...]:
        missing = []
        if not self.github_app_id:
            missing.append("GITHUB_APP_ID")
        if not self.github_private_key:
            missing.append("GITHUB_PRIVATE_KEY")
        if not self.github_webhook_secret:
            missing.append("GITHUB_WEBHOOK_SECRET")
        if not self.api_key:
            missing.append("GROQ_API_KEY" if self.llm_provider == "groq" else "OPENAI_API_KEY")
        return tuple(missing)

    def validate_runtime(self) -> None:
        missing = self.missing_runtime_variables()
        if missing:
            raise ValueError(f"Missing required environment variables: {', '.join(missing)}")

    def should_review_path(self, path: str) -> bool:
        suffix = Path(path).suffix.lower()
        if suffix not in self.reviewable_extensions:
            return False
        if self.include_patterns and not any(Path(path).match(pattern) for pattern in self.include_patterns):
            return False
        if any(Path(path).match(pattern) for pattern in self.exclude_patterns):
            return False
        return True

    def should_ignore_pr(self, text: str) -> bool:
        lowered = text.lower()
        return any(keyword.lower() in lowered for keyword in self.ignore_keywords)

    def is_summary_only(self, text: str) -> bool:
        lowered = text.lower()
        return any(keyword.lower() in lowered for keyword in self.summary_only_keywords)

    def is_bot_mentioned(self, text: str) -> bool:
        lowered = text.lower()
        return any(alias.lower() in lowered for alias in self.bot_aliases)

    def extract_staff_review_prompt(self, text: str) -> str | None:
        stripped = text.strip()
        lowered = stripped.lower()
        for command in self.staff_review_commands:
            normalized = command.strip()
            if not normalized:
                continue
            normalized_lower = normalized.lower()
            if lowered == normalized_lower:
                return ""
            prefix = f"{normalized_lower} "
            if lowered.startswith(prefix):
                return stripped[len(normalized):].strip()
        return None

    def with_overrides(self, overrides: dict[str, Any]) -> "Settings":
        allowed = {
            "review_model",
            "summary_model",
            "fallback_review_model",
            "fallback_summary_model",
            "max_files_to_review",
            "max_comments_per_review",
            "review_simple_changes",
            "post_review_summary",
            "enable_incremental_reviews",
            "enable_conversation",
            "enable_test_plan",
            "include_patterns",
            "exclude_patterns",
            "ignore_keywords",
            "summary_only_keywords",
            "staff_review_commands",
            "bot_aliases",
            "generated_markers",
        }
        normalized = {key: value for key, value in overrides.items() if key in allowed and value is not None}
        merged = self.model_dump()
        merged.update(normalized)
        return Settings.model_validate(merged)


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()


def parse_repo_config(content: str) -> dict[str, Any]:
    data = tomllib.loads(content)
    section = data.get("review") or data.get("pr_review_agent") or data
    if not isinstance(section, dict):
        return {}
    return section
